#!/bin/bash

# This was generated by Claude purely based on "mcpc --help"
# Company Lookup Script using mcpc + Apify RAG Web Browser
# Usage: ./company-lookup.sh "Company Name"

COMPANY="${1:-}"

if [ -z "$COMPANY" ]; then
    echo "Usage: $0 \"Company Name\""
    echo "Example: $0 \"Stripe\""
    exit 1
fi

echo "🔍 Looking up: $COMPANY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏳ Searching the web..."
echo ""

# Build the query - company name + search terms
QUERY="${COMPANY} company headquarters address"

# Use mcpc with the RAG web browser to fetch results as JSON
# Note: We need to be careful with quoting to preserve spaces in the query
MARKDOWN=$(mcpc @test tools-call apify-slash-rag-web-browser \
    "query:=${QUERY}" \
    'maxResults:=1' \
    'outputFormats:=["markdown"]' \
    --json 2>/dev/null \
    | jq -r '.content[0].text // empty' 2>/dev/null \
    | jq -r '.[0].markdown // empty' 2>/dev/null)

# Check if we got results
if [ -z "$MARKDOWN" ]; then
    echo "❌ No results found for '$COMPANY'"
    echo ""
    echo "Trying alternative search..."

    # Fallback: try simpler query
    MARKDOWN=$(mcpc @test tools-call apify-slash-rag-web-browser \
        "query:=https://www.google.com/search?q=${COMPANY// /+}+company" \
        'maxResults:=1' \
        'outputFormats:=["markdown"]' \
        --json 2>/dev/null \
        | jq -r '.content[0].text // empty' 2>/dev/null \
        | jq -r '.[0].markdown // empty' 2>/dev/null)

    if [ -z "$MARKDOWN" ]; then
        echo "❌ Still no results. Try a different company name."
        exit 1
    fi
fi

echo "📄 Company Information:"
echo "────────────────────────────────────────────────────"
# Show first 50 lines of markdown
echo "$MARKDOWN" | head -50

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Done"
